package GameGUI;

import javax.swing.*;
import java.awt.*;

public class TestingGif extends JPanel {
    public JPanel panel1;
    public JLabel gif;
    public JTextField gifTestinGJavaTextField;

    public static void gifMaker() {
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("TestingGif");
        frame.setContentPane(new TestingGif().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        gif = new JLabel();
        gif.setText("");
        panel1.add(gif, BorderLayout.CENTER);
        gifTestinGJavaTextField = new JTextField();
        gifTestinGJavaTextField.setText("gif testin g java");
        panel1.add(gifTestinGJavaTextField, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}

